- name: HTMLProofer
  # You may pin to the exact commit or the version.
  # uses: chabad360/htmlproofer@c2750eb7eb937599ac859517e7dd23a29f1b3ed7
  uses: chabad360/htmlproofer@v2
  with:
    # The directory to scan
    directory: 
    # HTMLProofer options
    arguments: # optional
